# SPRING CONFIGS
spring:
  application:
    name: event-core
  # DATABASE CONFIGS
  datasource:
    url: jdbc:postgresql://localhost:5432/event_core
    username: postgres
    password: richardeveloper
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
# OTHER CONFIGS
server:
  port: 8080