# SPRING CONFIGURATIONS
spring:
  application:
    name: event-core
# DATABASE CONFIGURATIONS
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
# RABBITMQ CONFIGURATIONS
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
    queues:
      confirmacao-inscricao: confirmacao_inscricao
      cancelamento-inscricao: cancelamento_inscricao
      alteracao-data-evento: alteracao_data_evento
      inicio-evento: inicio_evento
      fim-evento: fim_evento
      cancelamento-evento: cancelamento_evento
# OTHER CONFIGURATIONS
server:
  port: 8080
