# SPRING CONFIGURATIONS
spring:
  application:
    name: event-core
# DATABASE CONFIGURATIONS
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
# RABBITMQ CONFIGURATIONS
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
# OTHER CONFIGURATIONS
server:
  port: 8080
