# SPRING CONFIGS
spring:
  application:
    name: event-core
# DATABASE CONFIGS
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
# RABBITMQ CONFIGS
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
# OTHER CONFIGS
server:
  port: 8080
