# SPRING CONFIGURATIONS
spring:
  application:
    name: event-core
# DATABASE CONFIGURATIONS
  datasource:
    url: jdbc:postgresql://localhost:5432/event_core
    username: postgres
    password: richardeveloper
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
# KAFKA CONFIGURATIONS
kafka:
  consumer:
    bootstrap-servers: localhost:9092
    group-id: event-core-consumer
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
    bootstrap-servers: localhost:9092
    key-deserializer: org.apache.kafka.common.serialization.StringSerializer
    value-deserializer: org.apache.kafka.common.serialization.StringSerializer
# OTHER CONFIGURATIONS
server:
  port: 8080
